Repository Poten-Day-017/family-recipes-backend, pull requests merged in 2024-02, with the labels that each got.

#8 기본세팅
  .github/ISSUE_TEMPLATE/daedaesonson-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/bside/familyrecipes/FamilyRecipesApplication.java
  src/main/resources/application.properties
  src/test/java/com/bside/familyrecipes/FamilyRecipesApplicationTests.java
Labels: size/XS

#5 [FEAT🛠️] JWT TOKEN 적용
  build.gradle
  src/main/java/com/bside/familyrecipes/common/message/ExceptionMessage.java
  src/main/java/com/bside/familyrecipes/config/AuthConfig.java
  src/main/java/com/bside/familyrecipes/config/WebConfig.java
  src/main/java/com/bside/familyrecipes/config/jwt/JwtTokenManager.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feat, size/S

#7 [FEAT🛠️] 레시피 목록/상세 조회 기능 개발
  src/main/java/com/bside/familyrecipes/common/domain/BaseEntity.java
  src/main/java/com/bside/familyrecipes/common/dto/response/ErrorDto.java
  src/main/java/com/bside/familyrecipes/common/dto/response/ResponseDto.java
  src/main/java/com/bside/familyrecipes/config/SwaggerConfig.java
  src/main/java/com/bside/familyrecipes/error/ErrorType.java
  src/main/java/com/bside/familyrecipes/error/GlobalExceptionHandler.java
  src/main/java/com/bside/familyrecipes/error/exception/BusinessException.java
  src/main/java/com/bside/familyrecipes/error/exception/RecipeNotFoundException.java
  src/main/java/com/bside/familyrecipes/recipes/application/RecipeService.java
  src/main/java/com/bside/familyrecipes/recipes/converter/CategoryAttributeConverter.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Category.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Ingredient.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Procedure.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Recipe.java
  src/main/java/com/bside/familyrecipes/recipes/dto/request/RecipeCreateRequest.java
  src/main/java/com/bside/familyrecipes/recipes/dto/response/RecipeCategoryResponse.java
  src/main/java/com/bside/familyrecipes/recipes/dto/response/RecipeDetailResponse.java
  src/main/java/com/bside/familyrecipes/recipes/dto/response/RecipeListResponse.java
  src/main/java/com/bside/familyrecipes/recipes/facade/RecipeFacade.java
  src/main/java/com/bside/familyrecipes/recipes/presentation/RecipeController.java
  src/main/java/com/bside/familyrecipes/recipes/repository/IngredientRepository.java
  src/main/java/com/bside/familyrecipes/recipes/repository/ProcedureRepository.java
  src/main/java/com/bside/familyrecipes/recipes/repository/RecipeRepository.java
  src/main/resources/sql/init-data.sql
Labels: enhancement

#12 Feat/#11 레시피 등록 기능 개발
  src/main/java/com/bside/familyrecipes/FamilyRecipesApplication.java
  src/main/java/com/bside/familyrecipes/config/SecurityConfig.java
  src/main/java/com/bside/familyrecipes/error/ErrorType.java
  src/main/java/com/bside/familyrecipes/error/exception/CreateRecipeFailException.java
  src/main/java/com/bside/familyrecipes/error/exception/FileUploadException.java
  src/main/java/com/bside/familyrecipes/recipes/application/RecipeService.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Category.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Ingredient.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Procedure.java
  src/main/java/com/bside/familyrecipes/recipes/domain/Recipe.java
  src/main/java/com/bside/familyrecipes/recipes/dto/request/RecipeCreateRequest.java
  src/main/java/com/bside/familyrecipes/recipes/dto/response/RecipeDetailResponse.java
  src/main/java/com/bside/familyrecipes/recipes/dto/response/RecipeListResponse.java
  src/main/java/com/bside/familyrecipes/recipes/facade/RecipeFacade.java
  src/main/java/com/bside/familyrecipes/recipes/presentation/RecipeController.java
  src/main/java/com/bside/familyrecipes/recipes/repository/RecipeRepository.java
  src/main/java/com/bside/familyrecipes/storage/application/StorageService.java
  src/main/resources/application.yml
  src/main/resources/sql/init-data.sql
Labels: feat

#14 [FEAT🛠️] 로그인 수정 + relogin api 개발
  src/main/java/com/bside/familyrecipes/social/application/KakaoSocialService.java
  src/main/java/com/bside/familyrecipes/social/application/SocialCommonService.java
  src/main/java/com/bside/familyrecipes/social/application/SocialCommonServiceImpl.java
  src/main/java/com/bside/familyrecipes/social/dto/request/SocialLoginRequestDTO.java
  src/main/java/com/bside/familyrecipes/users/domain/User.java
Labels: feat, size/S

#17 Feat/#6 get user profile
  src/main/java/com/bside/familyrecipes/social/application/KakaoSocialService.java
  src/main/java/com/bside/familyrecipes/social/application/SocialCommonService.java
  src/main/java/com/bside/familyrecipes/social/application/SocialCommonServiceImpl.java
  src/main/java/com/bside/familyrecipes/social/dto/request/SocialLoginRequestDTO.java
  src/main/java/com/bside/familyrecipes/users/domain/User.java
Labels: feat, size/S
